[package]
name = "rtt-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.41.1", features = [
    "full",
] }
anyhow = "1.0.100"
statrs = "0.18.0"
bincode = "2.0.1"
serde = { version = "1.0.228", features = ["derive"] }
chrono = "0.4.42"
plotters="*"
